### PR TITLE
Corrected Message UBX-CFG-NAVX5.

### PR DESCRIPTION
**Pull request by Nerolf05**
# pyubx2 Pull Request Template

## Description

Fixed wrong payload definition of UBX-CFG-NAVX5 in ubxtypes_set.py

## Testing

Tested with a M8N-ublox receiver.

## Checklist:

- [x] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [x] I have tested my code against the full `tests/test_*.py` unittest suite.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Comment by semuadmin** [comment]
Hi Nerolf05. Good spot. I note there are actually two versions of this message type - one for M98N protocols 15-17, and another for protocols 18-22, but the following version from the M8N Interface Specification seems to accommodate both (this uses very slightly different nomenclature from yours - see note below):

    "CFG-NAVX5": {
        "version": U2,
        "mask1": X2,
        "mask2": X4,
        "reserved1": U2,
        "minSVs": U1,
        "maxSVs": U1,
        "minCNO": U1,
        "reserved2": U1,
        "iniFix3D": U1,
        "reserved3": U2,
        "ackAiding": U1,
        "wknRollover": U2,
        "sigAttenCompMode": U1,
        "reserved4": U1,
        "reserved5": U2,
        "reserved6": U2,
        "usePPP": U1,
        "aopCfg": U1,
        "reserved7": U2,
        "aopOrbMaxErr": U2,
        "reserved8": U4,
        "reserved9": U3,
        "useAdr": U1,
    },

(UBX seem to be using "minCNO" rather than "minCN0", although the field does of course refer to C/N 0. The reserved fields also start from "reserved1" in my spec)

The change will need to be made in both ubxtypes_set.py and ubxtypes_get.py. If you're happy to make these changes, we're good.

**Comment by Nerolf05** [comment]
Thank you for your fast reply.
I applied the proposed changes and successfully ran the complete test suit without any error.

**Comment by semuadmin** [comment]
OK thanks. FYI there has been an issue over the past few weeks with GitHub's CodeCov workflow action which has been causing some merges to fail through no fault of the contributor. Hopefully it's been resolved now, but it has been a bit hit-and-miss for a while now.

**Comment by Nerolf05** [comment]
One last question regarding this PR#21:
* Do you know when the next version 1.0.12 of pyubx2-module will be available?

**Comment by semuadmin** [comment]
How about today?

**Pull request merged**
