### PR TITLE
Handle UBX-NAV-PL messages

### PR DESCRIPTION
**Pull request by ArrEssJay**
## Description

Handle NAV-PL messages. These were not being parsed, causing an exception to be raised in the parser when present in a stream. 

This exception causes a stall of [PyGPSClient](https://github.com/semuconsulting/PyGPSClient) when attempting to parse a live stream from a TCP socket.

This change does not address the exception handling.

Reference: [u-blox F9 HPG 1.32 - Interface Description](https://content.u-blox.com/sites/default/files/documents/u-blox-F9-HPG-1.32_InterfaceDescription_UBX-22008968.pdf)

Added parser and sample message test case.
[Log file containing NAV-PL messages](https://www.dropbox.com/s/5714qlav45sufpj/nav-pl.log?dl=0)

## Testing

Added test case in `test_parse.py` (message generated by an F9P rx.)

## Checklist:

- [*] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [*] I have performed a self-review of my own code.
- [*] (*if appropriate*) I have cited my u-blox documentation source(s).
- [-] I have commented my code, particularly in hard-to-understand areas.
- [-] I have made corresponding changes to the documentation.
- [*] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [*] I have tested my code against the full `tests/test_*.py` unittest suite.
- [*] My changes generate no new warnings.
- [-] Any dependent changes have been merged and published in downstream modules.
- [*] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Review by semuadmin — CHANGES_REQUESTED** [review]
Hi @ArrEssJay 

PR very much appreciated. I think NAV-PL is new to HPG 1.30.

Code is fine but could I request a couple of very small and pedantic changes for consistency:

1) rename `version` to `msgversion` as per the written specification and to avoid any confusion with the `pyubx2.version` property.
2) move the NAV-PL message definition in `ubxtypes_get.py` to _after_ NAV-ORB rather than before it, to keep the definitions in ascending alphabetical order.

Many thanks

**Comment by semuadmin** [comment]
FYI I'll improve the socket exception handling in PyGPSClient in the next release to address https://github.com/semuconsulting/PyGPSClient/issues/22

**Comment by ArrEssJay** [comment]
Changes requested seemed appropriate, not pedantic. I missed the ordering in `ubxtypes_get.py`. Thanks for correcting.

**Comment by semuadmin** [comment]
Hi @ArrEssJay 

Purely out of interest, is your F9P actually running HPG 1.32? I've seen the documentation but I couldn't find a downloadable firmware file on the ublox site. The latest I have is 1.30.

**Comment by ArrEssJay** [comment]
I read the release notes and decided it wasn't worth upgrading the receiver
from 1.30. I just checked and don't see the 1.32 firmware image available
for download either.

**Pull request merged**
