### PR TITLE
Added generation 9 CFG-VALDEL, CFG-VALGET and CFG-VALSET messages

### PR DESCRIPTION
**Pull request by mgesteiro**
Added support for de generation 9 CFG-VALDEL, CFG-VALGET and CFG-VALSET messages, along with sample code.

### CODE REVIEW

**Comment by mgesteiro** [comment]
wow! We were working on the same stuff at the same time!! 😅😅😅

I believe that your ubxtypes_poll.py  CFG-VALGET definition is incorrect (this message receives variable length fields)

I'll sugest to use "cfgData" for the group name instead of the content data, for me it's less confusing as de content is just data (again, variable length fields).

nice work!

**Comment by semuadmin** [comment]
FYI I've been using u-blox's NEO9 interface description https://www.u-blox.com/en/docs/UBX-19035940 for the CFG-VALGET, CFG-VALSET, CFG-VALDEL payload definitions. These appear to be consistent with your revised source.

In terms of payload naming conventions, the name of the repeating group is essentially arbitrary and is not actually used in the parsing routine, but I would prefer to keep the names of the actual individual repeating data items consistent with the documented u-blox specification.

But the worked examples are useful - thanks for these. We'll review and get back to you asap.

**Comment by mgesteiro** [comment]
> FYI I've been using u-blox's NEO9 interface description https://www.u-blox.com/en/docs/UBX-19035940 for the CFG-VALGET, CFG-VALSET, CFG-VALDEL payload definitions. These appear to be consistent with your revised source.

The protocol is the same for (I believe) all generation 9 devices. I've been using this other document: https://www.u-blox.com/en/docs/UBX-18010854
 
> In terms of payload naming conventions, the name of the repeating group is essentially arbitrary and is not actually used in the parsing routine, but I would prefer to keep the names of the actual individual repeating data items consistent with the documented u-blox specification.

I agree.
The issue that I found was when trying to build a message based on these fields (e.g. cfgData=b"\xHH\xHH\xHH\xHH" vs group=b"\xHH\xHH\xHH\xHH"), but as you stated in your changes, "data must be set via payload". It would be nice to be able to construct the message using these fields, but that's a lot of work right now.
 
> But the worked examples are useful - thanks for these. We'll review and get back to you asap.

you're wellcome!

**Comment by semuadmin** [comment]
Hi. As you may have seen, we're branching the UBX configuration database work with a view to providing dedicated parse and construct methods for the NEO-9+ generation CFG-VALGET, CFG-VALSET and CFG-VALDEL message types in due course. Currently a work in progress so please watch this space. Given that this area is something of a moving target at the moment, I'll close this PR for now but appreciate the input.

**Pull request closed without merging**
