### PR TITLE
Added in more of the msgout keys

### PR DESCRIPTION
**Pull request by cturvey**
Ground thru the source materials scouring for missing/changed keys
Improved the export and sorting of my own tables to more closely match the Python tables used to ease merging on my side

-Clive

HPG 1.20, HPG 1.30 HPS 1.21 PMP 1.04
uCenter (Classic / 2,0)

# pyubx2 Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Testing

Please test all changes, however trivial, against the supplied unittest suite `tests/test_*.py` e.g. by executing the `tests/testsuite.py`
module or using your IDE's native Python unittest integration facilities.
Please describe any test cases you have amended or added to this suite to maintain >= 99% code coverage.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [ ] I have tested my code against the full `tests/test_*.py` unittest suite.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Comment by cturvey** [comment]
Low order RTCM3 messages can be found in ZED-F9T TIM 2.13
ZED-F9T-10B_InterfaceDescription_UBX-20033631.pdf

**Comment by semuadmin** [comment]
Hi again @cturvey. Very much appreciate these contributions and happy to merge but must confess to being very slightly wary about the provenance, particularly as I'm publishing under a BSD-2 license.  To date, I've been obtaining UBX payload definitions and configuration database keys from what are effectively public-domain u-blox interface specification documents (I actually have some macros which automatically collate and format the data from PDF sources - they're not 100% foolproof but they minimise the manual transcription effort involved). I know you're an authoratative presence on the u-blox support forums so I don't for a minute doubt the accuracy of this information, but is it available in public-domain interface specification documents or are we effectively 'reverse-engineering' u-center?

For example, I can find no reference to a `UBX-NAV-PVAT` message type in any published interface specification, though I note you have referenced it in response to some support forum queries. Which specific devices support this?

I can't see u-blox having any issue with this, but I'd like to ensure I'm on solid ground.

**Review by semuadmin — APPROVED** [review]
Looks Good. I've removed one duplicate entry (CFG_HW_ANT_CFG_OPENDET_POL) and  moved the  CFG_MSGOUT_UBX_DBG_31* entries to maintain alphabetical sort order. 

It appears we're missing payload definitions for the following UBX message types, which I'll aim to rectify in the next release (if you have definitions to hand, that would be useful): 
MON-SYS
NAV-PVAT
NAV2-EELL
NAV2-PVAT
RXM-ALM
RXM-COR
RXM-EPH
RXM-QZSSL6
RXM-SPARTN
RXM-TM

**Comment by cturvey** [comment]
https://s-taka.org/en/zed-f9p-new-firmware-hpg130/

**Comment by semuadmin** [comment]
I did wonder about your relationship with u-blox as you seem to be single-handedly carrying their support forum :-) Sadly I have no such relationship (_even our attempts to blag HPG RTK devkit for testing purposes were rebuffed!_), so I've tended to exercise caution and stick to official 'public-domain' PDF sources and a trusty (_whisper it_) VBA macro, which explains the occasional omission. I have come across a few undocumented MSGOUT configdb keys in testing which may well be the ones you mention. I've added in definitions for MON-SYS, NAV-PVAT, NAV2-EELL, NAV2-PVAT, RXM-COR, RXM-QZSSL6, RXM-SPARTN, RXM-SPARTN-KEY & RXM-TM. I believe RXM-ALM and RXM-EPH are now obsolete but I appreciate the links and will add these in for completeness (_I have considered parsing alm and eph data from RXM-SFRBX but it obviously involves aggregating time series data and I want to keep pyubx2 as a single-pass parser for the time being_). Thanks again for the contributions.

**Comment by cturvey** [comment]
HPS 1.20
https://drive.google.com/file/d/1aF8wB9Jfg5oFsz13_Z-DaHZqqvtRgkUV/view?usp=sharing

HPS 1.21
https://drive.google.com/file/d/18IVLn0l_VV4rU1v5t3u8vuKln3omrLcG/view?usp=sharing

**Comment by cturvey** [comment]
I used to work for NavSync, the legacy hardware spin-out of the Parthus-Ceva designs, which date back to the original Polytechnic Electronics / Navstar Systems Ltd designs. The uBlox 4 design was an Atmel build of the Ceva GPS engine with an ARM7, so I have some common understanding of the internal mechanics, at least historically.  I worked on some of the firmware used on the NS3000 (NS3K) which was a Ceva design with an ARM926, as  I recall, fabbed by Samsung. I also worked on some of the legacy firmware for the XR5 and Sharpe-XR6 designs, the latter being a 12-Channel GPS L1 RTK receiver. The IC people went thru a couple of name/owners until Glonav were subsumed by Intel.
I did push uBlox hard to develop the NEO-M8P when the path to sub-$400 RTK receivers wasn't clear enough.
I did buy my own SwiftNav and ArduSimple boards, and developed chip and module level GNSS receivers.

**Pull request merged**
