### PR TITLE
Feature/fix templates

### PR DESCRIPTION
**Pull request by Hadatko**
# pyubx2 Pull Request Template

## Description

This PR is fixing markdown issues + hidding tips for creating issue/pr in output which will make it more transparent.

## Testing

Please test all changes, however trivial, against the supplied unittest suite `tests/test_*.py` e.g. by executing the `tests/testsuite.py` module or using your IDE's native Python unittest integration facilities.
Please describe any test cases you have amended or added to this suite to maintain >= 99% code coverage.

- [ ] Test A
- [ ] Test B

## Checklist:

- [X] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [X] I have performed a self-review of my own code.
- [ ] (*if appropriate*) I have cited my u-blox documentation source(s).
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [ ] I have tested my code against the full `tests/test_*.py` unittest suite.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Comment by semuadmin** [comment]
Hi @Hadatko I'm sorry, but it's not clear to me what the purpose or objectives of this change are? I'm not aware of any significant issues with the PR template. Can you expand on the motivation and what problem you feel is being addressed here?

**Comment by Hadatko** [comment]
When user is creating pr/issue you are providing aditional text which is informing user about details. These information are not more needed after PR is created as all information were filled and pushed. So changing them to markdown comments you will have cleaner PR/ISSUE detail, but still available for user in time of creation.

**Comment by semuadmin** [comment]
Appreciate the contribution but I'm not convinced this is a worthwhile change. The PR template is not excessively verbose and retaining the full transcript after the merge is not particularly problematic.

**Comment by Hadatko** [comment]
No problem with your decision but you should consider use of first commit as it is fixing several markdown issues.

**Comment by semuadmin** [comment]
Hi @Hadatko FYI I've incorporated some minor template updates in a recent tidy-up push.

**Pull request closed without merging**
